---
title: "PCA analysis"
author: "GG"
date: "5/14/2018"
output: html_document
---

```{r}
library(vegan)

```
```{r}
PCA_fish <- read_csv("~/Desktop/Lionfish/Darwin_matrix.csv")
```

```{r}
library(tidyverse)
row.names(PCA_fish) <- PCA_fish$X1
PCA_fish[1] = NULL
```

```{r}
library(vegan)

```
```{r}
nmds <- metaMDS(PCA_fish,k=2,trymax=1000)
```
```{r}
plot(nmds)
```

```{r}
treat <- c(rep("Treatment1",6),rep("Treatment2",5))
ordiplot(nmds,type="n")
ordihull(nmds,groups=(treat),draw="polygon",col="grey90",label=F)
orditorp(nmds,display="species",col="black",air=0.01)
orditorp(nmds,display="sites",col=c(rep("red",6),rep("blue",5)),
   air=0.01,cex=1.25)
```

```{r}
nmds2 <- plot(nmds,display="sites", type="n")
orditorp(nmds,display="sites",cex=1.25,air=0.01)

```

Let's try this again using a K means cluster analysis...
```{r}
library(tidyverse)  # data manipulation
library(cluster)    # clustering algorithms
install.packages("factoextra")
library(factoextra)
```


```{r}
library(ggplot2)
cluster2 <- kmeans(PCA_fish, centers = 2, nstart = 25)
str(cluster2)
pcaplot <- fviz_cluster(cluster2, data = PCA_fish, fill = "darkblue") + ylim(-2.5,4.5) + theme_classic()
ggsave(PCA_fish, plot = pcaplot, device = "eps")
pcaplot
```


```{r}
ggpcaplot <- pcaplot + theme_classic() + labs(title="")
ggpcaplot
```
```{r}
cluster3 <- kmeans(PCA_fish, centers = 3, nstart = 25)
str(cluster3)
fviz_cluster(cluster3, data = PCA_fish, fill = "darkblue") + ylim(-2.5,4.5) + theme_classic()
```


