---
title: "Darwin"
author: "GG"
date: "5/8/2018"
output: html_document
---
#Darwin Correlation Analyses
```{r}
library(ggplot2)
library(tidyverse)
library(readxl)
library(janitor)
library(dbplyr)
```

```{r}
darwin <- read_csv("~/Documents/darwin_stats.csv")
```

```{r}
ggplot(data = darwin, aes(y = as.numeric(lionfish_den), x = fish_div)) + geom_point() + geom_smooth(method='lm',formula=y~x)
```

```{r}
ggplot(data = darwin, aes(y = as.numeric(lionfish_den), x = fish_den)) + geom_point() + geom_smooth(method='lm',formula=y~x)
```
```{r}
ggplot(data = darwin, aes(y = as.numeric(lionfish_den), x = fish_bio)) + geom_point() + geom_smooth(method='lm',formula=y~x)
```

```{r}
ggplot(data = darwin, aes(y = as.numeric(lionfish_den), x = temp)) + geom_point() + geom_smooth(method='lm',formula=y~x)
```

```{r}
ggplot(data = darwin, aes(y = as.numeric(lionfish_den), x = c_bda)) + geom_point() + geom_smooth(method='lm',formula=y~x)
```

```{r}
ggplot(data = darwin, aes(y = as.numeric(lionfish_den), x = c_enchry)) + geom_point() + geom_smooth(method='lm',formula=y~x)
```

```{r}
ggplot(data = darwin, aes(y = as.numeric(lionfish_den), x = p_furc)) + geom_point() + geom_smooth(method='lm',formula=y~x)
```

```{r}
ggplot(data = darwin, aes(y = as.numeric(lionfish_den), x = fish_bio)) + geom_point() + geom_smooth(method='lm',formula=y~x)
```

```{r}
corr <- round(cor(darwin), 1)
```

```{r}
install.packages("ggcorrplot")
library(ggcorrplot)
corr <- round(cor(darwin), 1)
ggcorrplot(corr, hc.order = TRUE, 
           type = "lower", 
           lab = TRUE, 
           lab_size = 3, 
           method="circle", 
           colors = c("tomato2", "white", "springgreen3"), 
           title="Correlogram of mtcars", 
           ggtheme=theme_bw)
```
```{r}
p.mat <- cor_pmat(darwin)
p.mat

```

```{r}
ggcorrplot(corr, hc.order = TRUE, 
           type = "lower", 
           lab = TRUE, 
           lab_size = 3, 
           colors = c("tomato2", "white", "springgreen3"),
           p.mat = p.mat,
           title="Correlogram of Lionfish Density", 
           ggtheme=theme_bw)
```
```{r}
darwin_corr <- ggcorrplot(corr, hc.order = TRUE, 
           type = "lower", 
           outline.col = "white",
           p.mat = p.mat,
           title="Correlogram of Lionfish Density", 
           colors = c("darkblue", "white", "red"),
           ggtheme=theme_bw)
darwin_corr
ggsave(darwin, plot = darwin_corr, device = "eps", path = "~/Desktop/Lionfish")
```

```{r}

```





